# Messages: Customizable messages shown to players under specific conditions.
messages:
  no-permission: "&cYou don't have enough permissions!"
  unknown-apple: "&cUnknown type of apple: %apple_type%"

# Rarities: Defines rarity levels for apples, with display formats (e.g., color codes).
rarities:
  COMMON: "&7Common"
  RARE: "&9Rare" 

# Apples: Defines custom apples, including their appearance, behavior, and effects.
apples:
  # Unique identifier for the apple (e.g., 'test').
  test:
    display-name: "&7Test apple" 
    lore:
      - "&7Test lore lololol"
      - "&7Hello im &csnaily"
    # Rarity of the apple, must match a key from the 'rarities' section (e.g., COMMON, RARE).
    rarity: RARE
    # Minecraft material type for the apple (e.g., GOLDEN_APPLE, APPLE).
    material: GOLDEN_APPLE
    # Message broadcast when the apple is consumed. Set to false if want to disable
    broadcast: "&e%player%&/ ate a &a%apple_type%!"
    # Cooldown period (in seconds) before the apple can be used again.
    cooldown-seconds: 300
    # Effects applied to the player when the apple is consumed.
    effects:
      # Each effect has a type, level, and duration.
      - type: INCREASE_DAMAGE # Effect type (e.g., INCREASE_DAMAGE, SPEED, REGENERATION).
        level: 6              # Effect strength (e.g., 6 for Strength VI).
        duration-seconds: 300 # Duration of the effect in seconds.